version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - "6379:6379"

  test:
    build: .
    container_name: pptr
    environment:
      - REDIS_HOST=redis
      - DOCKER_ENV=true
    command: npm test
    depends_on:
      - redis
    volumes:
      - ./snapshots:/usr/src/app/snapshots
